<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up()
    {
        Schema::create('rayons', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('url');
            $table->string('value');
            $table->string('value2')->nullable();
            $table->smallInteger('city_id');
        });

        $sql = "
INSERT INTO `rayons` (`url`, `value`, `city_id`, `value2`) VALUES
('biryulevo-vostochnoe', 'Бирюлево Восточное', 1, 'Бирюлево Восточное'),
('biryulevo-zapadnoe', 'Бирюлево Западное', 1, 'Бирюлево Западное'),
('veshnyaki', 'Вешняки', 1, 'Вешняков'),
('vnukovo', 'Внуково', 1, 'Внуково'),
('degunino-vostochnoe', 'Дегунино Восточное', 1, 'Дегунино Восточное'),
('degunino-zapadnoe', 'Дегунино Западное', 1, 'Дегунино Западное'),
('desenovskoe', 'Десеновское', 1, 'Десеновском'),
('ivanovskoe', 'Ивановское', 1, 'Ивановском'),
('kapotnya', 'Капотня', 1, 'Капотни'),
('kokoshkino', 'Кокошкино', 1, 'Кокошкино'),
('kosino-uhtomskiy', 'Косино-Ухтомский', 1, 'Косино-Ухтомском'),
('kotlovka', 'Котловка', 1, 'Котловки'),
('kryukovo', 'Крюково', 1, 'Крюково'),
('kurkino', 'Куркино', 1, 'Куркино'),
('lianozovo', 'Лианозово', 1, 'Лианозово'),
('losinoostrovskiy', 'Лосиноостровский', 1, 'Лосиноостровском'),
('marfino', 'Марфино', 1, 'Марфино'),
('matushkino', 'Матушкино', 1, 'Матушкино'),
('medvedkovo-yughnoe', 'Медведково Южное', 1, 'Медведково Южное'),
('metrogorodok', 'Метрогородок', 1, 'Метрогородка'),
('mihaylovo-yarcevskoe', 'Михайлово-Ярцевское', 1, 'Михайлово-Ярцевское'),
('moghayskiy', 'Можайский', 1, 'Можайском'),
('molghaninovskiy', 'Молжаниновский', 1, 'Молжаниновском'),
('moskvorechye-saburovo', 'Москворечье-Сабурово', 1, 'Москворечье-Сабурово'),
('mosrentgen', 'Мосрентген', 1, 'Мосрентгена'),
('nekrasovka', 'Некрасовка', 1, 'Некрасовке'),
('novo-peredelkino', 'Ново-Переделкино', 1, 'Ново-Переделкино'),
('novofedorovskoe', 'Новофедоровское', 1, 'Новофедоровское'),
('ochakovo-matveevskoe', 'Очаково-Матвеевское', 1, 'Очаково-Матвеевском'),
('pervomayskoe', 'Первомайское', 1, 'Первомайском'),
('rogovskoe', 'Роговское', 1, 'Роговском'),
('ryazanovskoe', 'Рязановское', 1, 'Рязановском'),
('savelki', 'Савелки', 1, 'Савелках'),
('severnoe-tushino', 'Северное Тушино', 1, 'Северном Тушино'),
('silino', 'Силино', 1, 'Силино'),
('solncevo', 'Солнцево', 1, 'Солнцево'),
('sosenskoe', 'Сосенское', 1, 'Сосенском'),
('staroe-kryukovo', 'Старое Крюково', 1, 'Старом Крюково'),
('troick', 'Троицк', 1, 'Троицком'),
('filimonkovskoe', 'Филимонковское', 1, 'Филимонковском'),
('horoshevo-mnevniki', 'Хорошево-Мневники', 1, 'Хорошево-Мневники'),
('schapovskoe', 'Щаповское', 1, 'Щаповскоом'),
('scherbinka', 'Щербинка', 1, 'Щербинке'),
('yughnoe-tushino', 'Южное Тушино', 1, 'Южное Тушино'),
('yaroslavskiy', 'Ярославский', 1, 'Ярославском'),
('akademicheskiy', 'Академический', 1, 'Академическом'),
('alekseevskiy', 'Алексеевский', 1, 'Алексеевском'),
('arbat', 'Арбат', 1, 'Арбата'),
('aeroport', 'Аэропорт', 1, 'Аэропорта'),
('babushkinskiy', 'Бабушкинский', 1, 'Бабушкинском'),
('basmannyy', 'Басманный', 1, 'Басманном'),
('beskudnikovskiy', 'Бескудниковский', 1, 'Бескудниковском'),
('bibirevo', 'Бибирево', 1, 'Бибирево'),
('bogorodskoe', 'Богородское', 1, 'Богородском'),
('brateevo', 'Братеево', 1, 'Братеево'),
('butovo-severnoe', 'Бутово Северное', 1, 'Бутово Северное'),
('butovo-yughnoe', 'Бутово Южное', 1, 'Бутово Южное'),
('butyrskiy', 'Бутырский', 1, 'Бутырском'),
('voykovskiy', 'Войковский', 1, 'Войковском'),
('vyhino-ghulebino', 'Выхино-Жулебино', 1, 'Выхино-Жулебино'),
('gagarinskiy', 'Гагаринский', 1, 'Гагаринском'),
('golovinskiy', 'Головинский', 1, 'Головинском'),
('golyyanovo', 'Гольяново', 1, 'Гольяново'),
('danilovskiy', 'Даниловский', 1, 'Даниловском'),
('donskoy', 'Донской', 1, 'Донском'),
('dorogomilovo', 'Дорогомилово', 1, 'Дорогомилово'),
('zamoskvorechye', 'Замоскворечье', 1, 'Замоскворечье'),
('zyuzino', 'Зюзино', 1, 'Зюзино'),
('zyablikovo', 'Зябликово', 1, 'Зябликово'),
('izmaylovo', 'Измайлово', 1, 'Измайлово'),
('izmaylovo-severnoe', 'Измайлово Северное', 1, 'Измайлово Северное'),
('konykovo', 'Коньково', 1, 'Коньково'),
('koptevo', 'Коптево', 1, 'Коптево'),
('krasnogorsk', 'Красногорск', 1, 'Красногорском'),
('krasnoselyskiy', 'Красносельский', 1, 'Красносельском'),
('krylatskoe', 'Крылатское', 1, 'Крылатском'),
('kuzyminki', 'Кузьминки', 1, 'Кузьминок'),
('kuncevo', 'Кунцево', 1, 'Кунцево'),
('levobereghnyy', 'Левобережный', 1, 'Левобережном'),
('lefortovo', 'Лефортово', 1, 'Лефортово'),
('lyublino', 'Люблино', 1, 'Люблино'),
('maryina-roscha', 'Марьина Роща', 1, 'Марьиной Рощи'),
('maryino', 'Марьино', 1, 'Марьино'),
('medvedkovo-severnoe', 'Медведково Северное', 1, 'Медведково Северное'),
('meschanskiy', 'Мещанский', 1, 'Мещанском'),
('mitino', 'Митино', 1, 'Митино'),
('moskovskiy', 'Московский', 1, 'Московском'),
('nagatino-sadovniki', 'Нагатино-Садовники', 1, 'Нагатино-Садовники'),
('nagatinskiy-zaton', 'Нагатинский Затон', 1, 'Нагатинском Затоне'),
('nagornyy', 'Нагорный', 1, 'Нагорном'),
('nighegorodskiy', 'Нижегородский', 1, 'Нижегородском'),
('novogireevo', 'Новогиреево', 1, 'Новогиреево'),
('novokosino', 'Новокосино', 1, 'Новокосино'),
('obruchevskiy', 'Обручевский', 1, 'Обручевском'),
('orehovo-borisovo-severnoe', 'Орехово-Борисово Северное', 1, 'Орехово-Борисово Северное'),
('orehovo-borisovo-yughnoe', 'Орехово-Борисово Южное', 1, 'Орехово-Борисово Южное'),
('ostankinskiy', 'Останкинский', 1, 'Останкинском'),
('otradnoe', 'Отрадное', 1, 'Отрадном'),
('perovo', 'Перово', 1, 'Перово'),
('pechatniki', 'Печатники', 1, 'Печатниках'),
('pokrovskoe-streshnevo', 'Покровское-Стрешнево', 1, 'Покровское-Стрешнево'),
('preobraghenskoe', 'Преображенское', 1, 'Преображенском'),
('presnenskiy', 'Пресненский', 1, 'Пресненском'),
('prospekt-vernadskogo', 'Проспект Вернадского', 1, 'Проспект Вернадского'),
('ramenki', 'Раменки', 1, 'Раменках'),
('rostokino', 'Ростокино', 1, 'Ростокино'),
('ryazanskiy', 'Рязанский', 1, 'Рязанском'),
('savelovskiy', 'Савеловский', 1, 'Савеловском'),
('sviblovo', 'Свиблово', 1, 'Свиблово'),
('sokol', 'Сокол', 1, 'Сокол'),
('sokolinaya-gora', 'Соколиная Гора', 1, 'Соколиная Гора'),
('sokolyniki', 'Сокольники', 1, 'Сокольниках'),
('strogino', 'Строгино', 1, 'Строгино'),
('taganskiy', 'Таганский', 1, 'Таганском'),
('tverskoy', 'Тверской', 1, 'Тверском'),
('tekstilyschiki', 'Текстильщики', 1, 'Текстильщиках'),
('timiryazevskiy', 'Тимирязевский', 1, 'Тимирязевском'),
('troparevo-nikulino', 'Тропарево-Никулино', 1, 'Тропарево-Никулино'),
('tushino-severnoe', 'Тушино Северное', 1, 'Тушино Северное'),
('tushino-yughnoe', 'Тушино Южное', 1, 'Тушино Южное'),
('filevskiy-park', 'Филевский Парк', 1, 'Филевском Парке'),
('fili-davydkovo', 'Фили-Давыдково', 1, 'Фили-Давыдково'),
('hamovniki', 'Хамовники', 1, 'Хамовниках'),
('hovrino', 'Ховрино', 1, 'Ховрино'),
('horoshevskiy', 'Хорошевский', 1, 'Хорошевском'),
('caricyno', 'Царицыно', 1, 'Царицыно'),
('cheremushki', 'Черемушки', 1, 'Черемушках'),
('chertanovo-severnoe', 'Чертаново Северное', 1, 'Чертаново Северное'),
('chertanovo-centralynoe', 'Чертаново Центральное', 1, 'Чертаново Центральное'),
('chertanovo-yughnoe', 'Чертаново Южное', 1, 'Чертаново Южное'),
('schukino', 'Щукино', 1, 'Щукино'),
('yughnoportovyy', 'Южнопортовый', 1, 'Южнопортовый'),
('yakimanka', 'Якиманка', 1, 'Якиманки'),
('yasenevo', 'Ясенево', 1, 'Ясенево'),
('severnoe_medvedkovo', 'Северное Медведково', 1, NULL),
('teplyy-stan', 'Тёплый Стан', 1, NULL),
('severnoe-izmaylovo', 'Северное Измайлово', 1, NULL),
('zapadnoe-degunino', 'Западное Дегунино', 1, NULL),
('centralynyy', 'Центральный', 1, NULL),
('zapadnyy', 'Западный', 1, NULL),
('admiraltejskij', 'Адмиралтейский', 161, NULL),
('vasileostrovskij', 'Василеостровский', 161, NULL),
('vyborgskij', 'Выборгский', 161, NULL),
('kalininskij', 'Калининский', 161, NULL),
('kirovskij', 'Кировский', 161, NULL),
('kolpinskij', 'Колпинский', 161, NULL),
('krasnogvardejskij', 'Красногвардейский', 161, NULL),
('krasnoselskij', 'Красносельский', 161, NULL),
('kronshtadtskij', 'Кронштадтский', 161, NULL),
('kurortnyj', 'Курортный', 161, NULL),
('moskovskij', 'Московский', 161, NULL),
('nevskij', 'Невский', 161, NULL),
('petrogradskij', 'Петроградский', 161, NULL),
('petrodvorcovyj', 'Петродворцовый', 161, NULL),
('primorskij', 'Приморский', 161, NULL),
('pushkinskij', 'Пушкинский', 161, NULL),
('frunzenskij', 'Фрунзенский', 161, NULL),
('centralnyj', 'Центральный', 161, NULL),
('voroshilovskij', 'Ворошиловский', 43, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 43, NULL),
('kirovskij', 'Кировский', 43, NULL),
('leninskij', 'Ленинский', 43, NULL),
('oktyabrskij', 'Октябрьский', 43, NULL),
('pervomajskij', 'Первомайский', 43, NULL),
('proletarskij', 'Пролетарский', 43, NULL),
('sovetskij', 'Советский', 43, NULL),
('varavino-faktoriya', 'Варавино-Фактория', 4, NULL),
('isakogorskij', 'Исакогорский', 4, NULL),
('lomonosovskij', 'Ломоносовский', 4, NULL),
('majmaksanskij', 'Маймаксанский', 4, NULL),
('oktyabrskij', 'Октябрьский', 4, NULL),
('majskaya-gorka', 'Майская Горка', 4, NULL),
('severnyj', 'Северный', 4, NULL),
('solombalskij', 'Соломбальский', 4, NULL),
('ciglomenskij', 'Цигломенский', 4, NULL),
('kirovskij', 'Кировский', 5, NULL),
('leninskij', 'Ленинский', 5, NULL),
('sovetskij', 'Советский', 5, NULL),
('trusovskij', 'Трусовский', 5, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 6, NULL),
('industrialnyj', 'Индустриальный', 6, NULL),
('leninskij', 'Ленинский', 6, NULL),
('oktyabrskij', 'Октябрьский', 6, NULL),
('centralnyj', 'Центральный', 6, NULL),
('vostochnyj', 'Восточный', 7, NULL),
('zapadnyj', 'Западный', 7, NULL),
('padunskij', 'Падунский', 179, NULL),
('pravoberezhnyj', 'Правобережный', 179, NULL),
('centralnyj', 'Центральный', 179, NULL),
('bezhickij', 'Бежицкий', 181, NULL),
('volodarskij', 'Володарский', 181, NULL),
('sovetskij', 'Советский', 181, NULL),
('fokinskij', 'Фокинский', 181, NULL),
('leninskij', 'Ленинский', 197, NULL),
('pervomajskij', 'Первомайский', 197, NULL),
('pervorechenskij', 'Первореченский', 197, NULL),
('sovetskij', 'Советский', 197, NULL),
('frunzenskij', 'Фрунзенский', 197, NULL),
('zaterechnyj', 'Затеречный', 198, NULL),
('iristonskij', 'Иристонский', 198, NULL),
('promyshlennyj', 'Промышленный', 198, NULL),
('severo-zapadnyj', 'Северо-Западный', 198, NULL),
('leninskij', 'Ленинский', 9, NULL),
('oktyabrskij', 'Октябрьский', 9, NULL),
('frunzenskij', 'Фрунзенский', 9, NULL),
('voroshilovskij', 'Ворошиловский', 10, NULL),
('dzerzhinskij', 'Дзержинский', 10, NULL),
('kirovskij', 'Кировский', 10, NULL),
('krasnoarmejskij', 'Красноармейский', 10, NULL),
('krasnooktyabrskij', 'Краснооктябрьский', 10, NULL),
('sovetskij', 'Советский', 10, NULL),
('traktorozavodskij', 'Тракторозаводский', 10, NULL),
('centralnyj', 'Центральный', 10, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 12, NULL),
('kominternovskij', 'Коминтерновский', 12, NULL),
('levoberezhnyj', 'Левобережный', 12, NULL),
('leninskij', 'Ленинский', 12, NULL),
('sovetskij', 'Советский', 12, NULL),
('centralnyj', 'Центральный', 12, NULL),
('ahmatovskij', 'Ахматовский', 222, NULL),
('bajsangurovskij', 'Байсангуровский', 222, NULL),
('visaitovskij', 'Висаитовский', 222, NULL),
('shejh-mansurovskij', 'Шейх-Мансуровский', 222, NULL),
('akademicheskij', 'Академический', 14, NULL),
('verh-isetskij', 'Верх-Исетский', 14, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 14, NULL),
('kirovskij', 'Кировский', 14, NULL),
('leninskij', 'Ленинский', 14, NULL),
('oktyabrskij', 'Октябрьский', 14, NULL),
('ordzhonikidzevskij', 'Орджоникидзевский', 14, NULL),
('chkalovskij', 'Чкаловский', 14, NULL),
('leninskij', 'Ленинский', 15, NULL),
('oktyabrskij', 'Октябрьский', 15, NULL),
('sovetskij', 'Советский', 15, NULL),
('frunzenskij', 'Фрунзенский', 15, NULL),
('industrialnyj', 'Индустриальный', 16, NULL),
('leninskij', 'Ленинский', 16, NULL),
('oktyabrskij', 'Октябрьский', 16, NULL),
('pervomajskij', 'Первомайский', 16, NULL),
('ustinovskij', 'Устиновский', 16, NULL),
('leninskij', 'Ленинский', 17, NULL),
('oktyabrskij', 'Октябрьский', 17, NULL),
('pravoberezhnyj', 'Правобережный', 17, NULL),
('sverdlovskij', 'Свердловский', 17, NULL),
('aviastroitelnyj', 'Авиастроительный', 19, NULL),
('vahitovskij', 'Вахитовский', 19, NULL),
('kirovskij', 'Кировский', 19, NULL),
('moskovskij', 'Московский', 19, NULL),
('novo-savinovskij', 'Ново-Савиновский', 19, NULL),
('privolzhskij', 'Приволжский', 19, NULL),
('sovetskij', 'Советский', 19, NULL),
('leningradskij', 'Ленинградский', 287, NULL),
('moskovskij', 'Московский', 287, NULL),
('centralnyj', 'Центральный', 287, NULL),
('leninskij', 'Ленинский', 20, NULL),
('moskovskij', 'Московский', 20, NULL),
('oktyabrskij', 'Октябрьский', 20, NULL),
('sinarskij', 'Синарский', 290, NULL),
('krasnogorskij', 'Красногорский', 290, NULL),
('zavodskij', 'Заводский', 21, NULL),
('kirovskij', 'Кировский', 21, NULL),
('leninskij', 'Ленинский', 21, NULL),
('rudnichnyj', 'Рудничный', 21, NULL),
('centralnyj', 'Центральный', 21, NULL),
('leninskij', 'Ленинский', 22, NULL),
('novovyatskij', 'Нововятский', 22, NULL),
('oktyabrskij', 'Октябрьский', 22, NULL),
('pervomajskij', 'Первомайский', 22, NULL),
('leninskij', 'Ленинский', 532, NULL),
('centralnyj', 'Центральный', 532, NULL),
('centralnyj', 'Центральный', 23, NULL),
('fabrichnyj', 'Фабричный', 23, NULL),
('zavolzhskij', 'Заволжский', 23, NULL),
('zapadnyj', 'Западный', 24, NULL),
('karasunskij', 'Карасунский', 24, NULL),
('prikubanskij', 'Прикубанский', 24, NULL),
('centralnyj', 'Центральный', 24, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 565, NULL),
('kirovskij', 'Кировский', 565, NULL),
('leninskij', 'Ленинский', 565, NULL),
('oktyabrskij', 'Октябрьский', 565, NULL),
('sverdlovskij', 'Свердловский', 565, NULL),
('sovetskij', 'Советский', 565, NULL),
('centralnyj', 'Центральный', 565, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 26, NULL),
('sejmskij', 'Сеймский', 26, NULL),
('centralnyj', 'Центральный', 26, NULL),
('levoberezhnyj', 'Левобережный', 27, NULL),
('oktyabrskij', 'Октябрьский', 27, NULL),
('pravoberezhnyj', 'Правобережный', 27, NULL),
('sovetskij', 'Советский', 27, NULL),
('leninskij', 'Ленинский', 28, NULL),
('pravoberezhnyj', 'Правобережный', 28, NULL),
('ordzhonikidzevskij', 'Орджоникидзевский', 28, NULL),
('kirovskij', 'Кировский', 451, NULL),
('leninskij', 'Ленинский', 451, NULL),
('sovetskij', 'Советский', 451, NULL),
('leninskij', 'Ленинский', 29, NULL),
('oktyabrskij', 'Октябрьский', 29, NULL),
('pervomajskij', 'Первомайский', 29, NULL),
('avtozavodskij', 'Автозаводский', 566, NULL),
('centralnyj', 'Центральный', 566, NULL),
('komsomolskij', 'Комсомольский', 566, NULL),
('altievskij', 'Альтиевский', 567, NULL),
('gamurzievskij', 'Гамурзиевский', 567, NULL),
('nasyr-kortskij', 'Насыр-Кортский', 567, NULL),
('centralnyj', 'Центральный', 567, NULL),
('avtozavodskij', 'Автозаводский', 31, NULL),
('kanavinskij', 'Канавинский', 31, NULL),
('leninskij', 'Ленинский', 31, NULL),
('moskovskij', 'Московский', 31, NULL),
('nizhegorodskij', 'Нижегородский', 31, NULL),
('priokskij', 'Приокский', 31, NULL),
('sovetskij', 'Советский', 31, NULL),
('sormovskij', 'Сормовский', 31, NULL),
('tagilstroevskij', 'Тагилстроевский', 32, NULL),
('leninskij', 'Ленинский', 32, NULL),
('dzerzhinskij', 'Дзержинский', 32, NULL),
('zavodskoj', 'Заводской', 33, NULL),
('kuzneckij', 'Кузнецкий', 33, NULL),
('kujbyshevskij', 'Куйбышевский', 33, NULL),
('novoilinskij', 'Новоильинский', 33, NULL),
('ordzhonikidzevskij', 'Орджоникидзевский', 33, NULL),
('centralnyj', 'Центральный', 33, NULL),
('vostochnyj', 'Восточный', 34, NULL),
('primorskij', 'Приморский', 34, NULL),
('centralnyj', 'Центральный', 34, NULL),
('yuzhnyj', 'Южный', 34, NULL),
('novorossijskij', 'Новороссийский', 34, NULL),
('dzerzhinskij', 'Дзержинский', 35, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 35, NULL),
('zaelcovskij', 'Заельцовский', 35, NULL),
('kalininskij', 'Калининский', 35, NULL),
('kirovskij', 'Кировский', 35, NULL),
('leninskij', 'Ленинский', 35, NULL),
('oktyabrskij', 'Октябрьский', 35, NULL),
('pervomajskij', 'Первомайский', 35, NULL),
('sovetskij', 'Советский', 35, NULL),
('centralnyj', 'Центральный', 35, NULL),
('kajerkan', 'Кайеркан', 403, NULL),
('talnah', 'Талнах', 403, NULL),
('centralnyj', 'Центральный', 403, NULL),
('kirovskij', 'Кировский', 36, NULL),
('leninskij', 'Ленинский', 36, NULL),
('oktyabrskij', 'Октябрьский', 36, NULL),
('sovetskij', 'Советский', 36, NULL),
('centralnyj', 'Центральный', 36, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 37, NULL),
('zavodskoj', 'Заводской', 37, NULL),
('severnyj', 'Северный', 37, NULL),
('sovetskij', 'Советский', 37, NULL),
('dzerzhinskij', 'Дзержинский', 38, NULL),
('leninskij', 'Ленинский', 38, NULL),
('promyshlennyj', 'Промышленный', 38, NULL),
('centralnyj', 'Центральный', 38, NULL),
('leninskij', 'Ленинский', 391, NULL),
('oktyabrskij', 'Октябрьский', 391, NULL),
('sovetskij', 'Советский', 391, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 39, NULL),
('leninskij', 'Ленинский', 39, NULL),
('oktyabrskij', 'Октябрьский', 39, NULL),
('pervomajskij', 'Первомайский', 39, NULL),
('dzerzhinskij', 'Дзержинский', 40, NULL),
('industrialnyj', 'Индустриальный', 40, NULL),
('kirovskij', 'Кировский', 40, NULL),
('leninskij', 'Ленинский', 40, NULL),
('motovilihinskij', 'Мотовилихинский', 40, NULL),
('ordzhonikidzevskij', 'Орджоникидзевский', 40, NULL),
('sverdlovskij', 'Свердловский', 40, NULL),
('zenkovskij', 'Зенковский', 355, NULL),
('rudnichnyj', 'Рудничный', 355, NULL),
('centralnyj', 'Центральный', 355, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 44, NULL),
('moskovskij', 'Московский', 44, NULL),
('oktyabrskij', 'Октябрьский', 44, NULL),
('sovetskij', 'Советский', 44, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 45, NULL),
('kirovskij', 'Кировский', 45, NULL),
('krasnoglinskij', 'Красноглинский', 45, NULL),
('kujbyshevskij', 'Куйбышевский', 45, NULL),
('leninskij', 'Ленинский', 45, NULL),
('oktyabrskij', 'Октябрьский', 45, NULL),
('promyshlennyj', 'Промышленный', 45, NULL),
('samarskij', 'Самарский', 45, NULL),
('sovetskij', 'Советский', 45, NULL),
('leninskij', 'Ленинский', 423, NULL),
('oktyabrskij', 'Октябрьский', 423, NULL),
('proletarskij', 'Пролетарский', 423, NULL),
('volzhskij', 'Волжский', 46, NULL),
('zavodskoj', 'Заводской', 46, NULL),
('kirovskij', 'Кировский', 46, NULL),
('leninskij', 'Ленинский', 46, NULL),
('oktyabrskij', 'Октябрьский', 46, NULL),
('frunzenskij', 'Фрунзенский', 46, NULL),
('balaklavskij', 'Балаклавский', 47, NULL),
('gagarinskij', 'Гагаринский', 47, NULL),
('leninskij', 'Ленинский', 47, NULL),
('nahimovskij', 'Нахимовский', 47, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 441, NULL),
('kievskij', 'Киевский', 441, NULL),
('centralnyj', 'Центральный', 441, NULL),
('zadneprovskij', 'Заднепровский', 442, NULL),
('leninskij', 'Ленинский', 442, NULL),
('promyshlennyj', 'Промышленный', 442, NULL),
('adlerskij', 'Адлерский', 342, NULL),
('lazarevskij', 'Лазаревский', 342, NULL),
('hostinskij', 'Хостинский', 342, NULL),
('centralnyj', 'Центральный', 342, NULL),
('leninskij', 'Ленинский', 344, NULL),
('oktyabrskij', 'Октябрьский', 344, NULL),
('promyshlennyj', 'Промышленный', 344, NULL),
('ehzhvinskij', 'Эжвинский', 301, NULL),
('leninskij', 'Ленинский', 50, NULL),
('oktyabrskij', 'Октябрьский', 50, NULL),
('sovetskij', 'Советский', 50, NULL),
('zavolzhskij', 'Заволжский', 51, NULL),
('moskovskij', 'Московский', 51, NULL),
('proletarskij', 'Пролетарский', 51, NULL),
('centralnyj', 'Центральный', 51, NULL),
('avtozavodskij', 'Автозаводский', 52, NULL),
('komsomolskij', 'Комсомольский', 52, NULL),
('centralnyj', 'Центральный', 52, NULL),
('kirovskij', 'Кировский', 53, NULL),
('leninskij', 'Ленинский', 53, NULL),
('oktyabrskij', 'Октябрьский', 53, NULL),
('sovetskij', 'Советский', 53, NULL),
('zarechenskij', 'Зареченский', 2, NULL),
('privokzalnyj', 'Привокзальный', 2, NULL),
('proletarskij', 'Пролетарский', 2, NULL),
('sovetskij', 'Советский', 2, NULL),
('centralnyj', 'Центральный', 2, NULL),
('vostochnyj', 'Восточный', 54, NULL),
('kalininskij', 'Калининский', 54, NULL),
('leninskij', 'Ленинский', 54, NULL),
('centralnyj', 'Центральный', 54, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 55, NULL),
('oktyabrskij', 'Октябрьский', 55, NULL),
('sovetskij', 'Советский', 55, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 56, NULL),
('zavolzhskij', 'Заволжский', 56, NULL),
('zasviyazhskij', 'Засвияжский', 56, NULL),
('leninskij', 'Ленинский', 56, NULL),
('dyomskij', 'Дёмский', 57, NULL),
('kalininskij', 'Калининский', 57, NULL),
('kirovskij', 'Кировский', 57, NULL),
('leninskij', 'Ленинский', 57, NULL),
('oktyabrskij', 'Октябрьский', 57, NULL),
('ordzhonikidzevskij', 'Орджоникидзевский', 57, NULL),
('sovetskij', 'Советский', 57, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 58, NULL),
('kirovskij', 'Кировский', 58, NULL),
('krasnoflotskij', 'Краснофлотский', 58, NULL),
('industrialnyj', 'Индустриальный', 58, NULL),
('centralnyj', 'Центральный', 58, NULL),
('kalininskij', 'Калининский', 59, NULL),
('leninskij', 'Ленинский', 59, NULL),
('moskovskij', 'Московский', 59, NULL),
('kalininskij', 'Калининский', 121, NULL),
('kurchatovskij', 'Курчатовский', 121, NULL),
('leninskij', 'Ленинский', 121, NULL),
('metallurgicheskij', 'Металлургический', 121, NULL),
('sovetskij', 'Советский', 121, NULL),
('traktorozavodskij', 'Тракторозаводский', 121, NULL),
('centralnyj', 'Центральный', 121, NULL),
('zheleznodorozhnyj', 'Железнодорожный', 102, NULL),
('ingodinskij', 'Ингодинский', 102, NULL),
('centralnyj', 'Центральный', 102, NULL),
('chernovskij', 'Черновский', 102, NULL),
('avtodorozhnyj', 'Автодорожный', 70, NULL),
('gagarinskij', 'Гагаринский', 70, NULL),
('gubinskij', 'Губинский', 70, NULL),
('oktyabrskij', 'Октябрьский', 70, NULL),
('promyshlennyj', 'Промышленный', 70, NULL),
('sajsarskij', 'Сайсарский', 70, NULL),
('stroitelnyj', 'Строительный', 70, NULL),
('centralnyj', 'Центральный', 70, NULL),
('dzerzhinskij', 'Дзержинский', 65, NULL),
('zavolzhskij', 'Заволжский', 65, 'Заволжский'),
('kirovskij', 'Кировский', 65, 'Кировский'),
('krasnoperekopskij', 'Красноперекопский', 65, 'Красноперекопский'),
('leninskij', 'Ленинский', 65, 'Ленинский'),
('frunzenskij', 'Фрунзенский', 65, 'Фрунзенский');
";

        DB::statement($sql);

    }

    public function down()
    {
        Schema::dropIfExists('rayons');
    }
};
